version: '3.1'

services:

  db:
    build:
      context: ./postgres
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - data:/var/lib/postgresql/data
      - ./:/workspace
    working_dir: /workspace

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  data:
    driver: local
